/*
    All information comes from http://www.realsimple.com/home-organizing/cleaning/laundry/how-do-laundry or personal knowledge.
*/

module.exports = {
    "shirt": "Separate colors and whites. Wash colors in cold water; whites in warm water. Hang drying is preferred.",
    "shirts": "Separate colors and whites. Wash colors in cold water; whites in warm water. Hang drying is preferred.",
    "button-down shirt": "Unbutton all buttons on shirt. Apply stain remover or water with liquid detergent over stains or the collar, and rub using a soft toothbrush. Wash in permanent-press setting.",
    "button-down shirts": "Unbutton all buttons on shirt. Apply stain remover or water with liquid detergent over stains or the collar, and rub using a soft toothbrush. Wash in permanent-press setting.",
    "sweater": "Wash cotton blends on gentle. Use a zippered pillow case for wool, cashmere, or fine cotton. Dry clean delicates like crochet and silk",
    "sweaters": "Wash cotton blends on gentle. Use a zippered pillow case for wool, cashmere, or fine cotton. Dry clean delicates like crochet and silk",
    "socks": "Separate colors and whites. Turn them inside out and wash normally.",
    "sock": "Separate colors and whites. Turn them inside out and wash normally.",
    "jeans": "Wash in cold water. Dry on low or machineedium. Take jeans out of the dryer when the seams and waistband are slightly damp to prevent overdrying.",
    "hat": "Wash cotton blends on gentle. Use a zippered pillow case for wool, cashmere, or fine cotton. Dry clean delicates like crochet and silk",
    "hats": "Wash cotton blends on gentle. Use a zippered pillow case for wool, cashmere, or fine cotton. Dry clean delicates like crochet and silk",
    "newspaper hat": "Keep out of the washer",
    "newsboy hat": "Keep out of the washer",
    "baseball cap": "Keep out of the washer",
    "baseball hat": "Keep out of the washer",
    "gloves": "Hand wash. Insert handle of a wooden spoon in one finger and set the spoon end on a vase. This helps retain the glove's shape.",
    "down coat": "Wash in warm water on the gentle cycle in a front loading machine. If you have a top loader, take your coat to the dry cleaners.",
    "polyester coat": "Wash in warm water on the gentle cycle in a front loading machine. If you have a top loader, take your coat to the dry cleaners.",
    "down coats": "Wash in warm water on the gentle cycle in a front loading machine. If you have a top loader, take your coat to the dry cleaners.",
    "polyester coats": "Wash in warm water on the gentle cycle in a front loading machine. If you have a top loader, take your coat to the dry cleaners.",
    "coats": "Wash in warm water on the gentle cycle in a front loading machine. If you have a top loader, take your coat to the dry cleaners.",
    "underwear": "Put into zippered mesh bags to to protect delicates. Wash in gentle cycle. Don't use dryer.",
    "bras": "Put into zippered mesh bags to to protect delicates. Wash in gentle cycle. Don't use dryer.",,
    "lingerie": "Hand wash. Soak for a few minutes in warm or cool water. Gently squeeze suds through the fabric and dry using a towel before hang drying.",
    "baby clothes": "Use an extremely mild detergent at first. When the baby starts eating solid foods, switch to a stain fighting detergent. Use warm water and tumble dry on low",
    "baby clothing": "Use an extremely mild detergent at first. When the baby starts eating solid foods, switch to a stain fighting detergent. Use warm water and tumble dry on low",
    "swimsuits": "Rinse well to remove chlorine or salt water. Wash by hand or machine just like your underwear. Air dry.",
    "swimsuit": "Rinse well to remove chlorine or salt water. Wash by hand or machine just like your underwear. Air dry.",
    "shapewear": "If there is under wire, use a mesh bag. Wash like underwear. Air dry or tumble dry on low.",
    "curtains": "Most need to be dry cleaned. Washable fabrics can be laundered separately in warm or cool water on a gentle cycle and air dried.",
    "curtain": "Most need to be dry cleaned. Washable fabrics can be laundered separately in warm or cool water on a gentle cycle and air dried.",
    "blankets": "Test for colorfastness. Wash nonwool blankets on gentle with cold water. Tumble dry on low or line-dry. Dry cleaning is best for wool.",
    "blanket": "Test for colorfastness. Wash nonwool blankets on gentle with cold water. Tumble dry on low or line-dry. Dry cleaning is best for wool",
    "rugs": "Use half the recommended amount of all purpose detergent and then air dry. Hire a carpet cleaner for special fibers.",
    "rug": "Use half the recommended amount of all purpose detergent and then air dry. Hire a carpet cleaner for special fibers.",
    "tablecloth": "Presoak in oxygen bleach to remove stains. Then wash in hot water and air dry. Use a dry cleaner if necessary.",
    "tablecloths": "Presoak in oxygen bleach to remove stains. Then wash in hot water and air dry. Use a dry cleaner if necessary.",
    "napkins": "Presoak in oxygen bleach to remove stains. Then wash in hot water and air dry. Use a dry cleaner if necessary.",
    "napkin": "Presoak in oxygen bleach to remove stains. Then wash in hot water and air dry. Use a dry cleaner if necessary.",
    "slipcovers": "Check material before washing. If the fabric is linen, cotton, or synthetic and it is preshrunk and colorfast, you can machine wash it separately in cold water on gentle.",
    "slipcover":  "Check material before washing. If the fabric is linen, cotton, or synthetic and it is preshrunk and colorfast, you can machine wash it separately in cold water on gentle.",
    "cushion cover":  "Check material before washing. If the fabric is linen, cotton, or synthetic and it is preshrunk and colorfast, you can machine wash it separately in cold water on gentle.",
    "cushion covers":  "Check material before washing. If the fabric is linen, cotton, or synthetic and it is preshrunk and colorfast, you can machine wash it separately in cold water on gentle.",
    "sheets": "Wash cotton, flannel, synthetics, bamboo, or modal sheets once a week in hot water; dry on low. Wash linen, silk, and sateen-weave cotton on gentle in cold water; dry on low or air dry.",
    "sheet": "Wash cotton, flannel, synthetics, bamboo, or modal sheets once a week in hot water; dry on low. Wash linen, silk, and sateen-weave cotton on gentle in cold water; dry on low or air dry.",
    "bedsheet": "Wash cotton, flannel, synthetics, bamboo, or modal sheets once a week in hot water; dry on low. Wash linen, silk, and sateen-weave cotton on gentle in cold water; dry on low or air dry.",
    "bedsheets": "Wash cotton, flannel, synthetics, bamboo, or modal sheets once a week in hot water; dry on low. Wash linen, silk, and sateen-weave cotton on gentle in cold water; dry on low or air dry.",
    "bed sheet": "Wash cotton, flannel, synthetics, bamboo, or modal sheets once a week in hot water; dry on low. Wash linen, silk, and sateen-weave cotton on gentle in cold water; dry on low or air dry.",
    "bed sheets": "Wash cotton, flannel, synthetics, bamboo, or modal sheets once a week in hot water; dry on low. Wash linen, silk, and sateen-weave cotton on gentle in cold water; dry on low or air dry.",
    "backpack": "Wash separately in cold water on gentle using a front-loader washer. Don't wash multicolored packs",
    "backpacks": "Wash separately in cold water on gentle using a front-loader washer. Don't wash multicolored packs",
    "bookbag": "Wash separately in cold water on gentle using a front-loader washer. Don't wash multicolored packs",
    "bookbags": "Wash separately in cold water on gentle using a front-loader washer. Don't wash multicolored packs",
    "purse": "Use an all-purpose detergent and then air-dry. Don't wash purses with sequins or other embellishments.",
    "purses": "Use an all-purpose detergent and then air-dry. Don't wash purses with sequins or other embellishments.",
    "tote bag": "Use an all-purpose detergent and then air-dry.",
    "tote bags": "Use an all-purpose detergent and then air-dry.",
    "laptop case": "Wash canvas, nylon, and microfiber cases in warm water and then air-dry. Don't wash padded cases.",
    "laptop cases": "Wash canvas, nylon, and microfiber cases in warm water and then air-dry. Don't wash padded cases.",
    "ipod case": "Wash canvas, nylon, and microfiber cases in warm water and then air-dry. Don't wash padded cases.",
    "ipod cases": "Wash canvas, nylon, and microfiber cases in warm water and then air-dry. Don't wash padded cases.",
    "ironing board cover": "Wash in warm water and then air-dry",
    "ironing board covers": "Wash in warm water and then air-dry",
    "sleeping bag": "Wash in a front-loader in warm water on gentle; use a mild detergent. Then dry on low or no heat.",
    "sleeping bags": "Wash in a front-loader in warm water on gentle; use a mild detergent. Then dry on low or no heat.",
    "car seat": "Use warm water and one and a half capfuls of all purpose detergent. Dry on low for five to ten minutes, then air dry.",
    "car seats": "Use warm water and one and a half capfuls of all purpose detergent. Dry on low for five to ten minutes, then air dry.",
    "high chair cover": "Use warm water and one and a half capfuls of all purpose detergent. Dry on low for five to ten minutes, then air dry.",
    "high chair covers": "Use warm water and one and a half capfuls of all purpose detergent. Dry on low for five to ten minutes, then air dry.",
    "footwear": "Wash canvas or leather sneakers in cold water. Put into mesh bags to keep laces to prevent damage to the machine. Dry on low for ten minutes, and then air dry for a day.",
    "shoes": "Wash canvas or leather sneakers in cold water. Put into mesh bags to keep laces to prevent damage to the machine. Dry on low for ten minutes, and then air dry for a day.",
    "shoe": "Wash canvas or leather sneakers in cold water. Put into mesh bags to keep laces to prevent damage to the machine. Dry on low for ten minutes, and then air dry for a day.",
    "oven mitt": "Wash in hot water using an all-purpose detergent, and then air dry",
    "oven mitts": "Wash in hot water using an all-purpose detergent, and then air dry",
    "sponge": "Wash in hot water using an all-purpose detergent, and then air dry",
    "sponges": "Wash in hot water using an all-purpose detergent, and then air dry",
    "cloth diapers": "Add bleach and mild detergent, and then dry on high",
    "cloth diaper": "Add bleach and mild detergent, and then dry on high",
    "travel pillow": "Put travel pillows into pillow cases so you can just wash the pillowcase. Don't wash the pillow.",
    "travel pillows": "Put travel pillows into pillow cases so you can just wash the pillowcase. Don't wash the pillow.",
    "bath toys": "Use warm water and all-purpose detergent. Throw toys in the wash with a hand towel to get the slime off.",
    "bath toy": "Use warm water and all-purpose detergent. Throw toys in the wash with a hand towel to get the slime off.",
    "pet bed cover": "Wash in cold water on gentle; use small loads, but on large-load settings. Tumble dry on low.",
    "pet bed covers": "Wash in cold water on gentle; use small loads, but on large-load settings. Tumble dry on low.",
    "pet bed": "Wash in cold water on gentle; use small loads, but on large-load settings. Tumble dry on low.",
    "dog bed": "Wash in cold water on gentle; use small loads, but on large-load settings. Tumble dry on low.",
    "cat bed": "Wash in cold water on gentle; use small loads, but on large-load settings. Tumble dry on low.",
    "collar": "Wash in cold water on gentle; use small loads, but on large-load settings. Tumble dry on low.",
    "collars": "Wash in cold water on gentle; use small loads, but on large-load settings. Tumble dry on low.",
    "leash": "Wash in cold water on gentle; use small loads, but on large-load settings. Tumble dry on low.",
    "leashes": "Wash in cold water on gentle; use small loads, but on large-load settings. Tumble dry on low.",
    "dish gloves": "Wash in warm water on gentle for four minutes. Air dry.",
    "sports gear": "Wash in warm water on gentle. Air dry.",
    "jersey": "Wash colored jerseys together. Don't wash with other clothes. Wash in cold water and hang dry.",
    "basketball nets": "Wash in warm water on gentle. Air dry.",
    "shin guard": "Wash in warm water on gentle. Air dry.",
    "toys": "Wash cloth toys in cold water on gentle using a mild detergent. Dry on low for 5minutes then air dry. Hand wash for other kinds of toys.",
    "money": "That's illegal.",
    "cash": "That's illegal",
};
